sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t marcowilm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marcowilm/react-test npm test

after_success:
  - docker build -t marcowilm/multi-client ./client
  - docker build -t marcowilm/multi-nginx ./nginx
  - docker build -t marcowilm/multi-server ./server
  - docker build -t marcowilm/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to dockerhub
  - docker push marcowilm/multi-client
  - docker push marcowilm/multi-nginx
  - docker push marcowilm/multi-server
  - docker push marcowilm/multi-worker